Player rank added on every game, totalDeath added and fixes have been made
Androz2091/funcraft pull request #13
Opened 2020-03-26 02:54 UTC by Hunam6

2020-03-26 07:57 UTC, Androz2091 requested changes

2020-03-26 07:57 UTC, Androz2091 commented on structures/BlitzStats.js
> +        if (issue === false) return parseInt(stats.children[3].children[3].children[1].children[0].data);
```suggestion
        if (!issue) return parseInt(stats.children[3].children[3].children[1].children[0].data);
```

2020-03-26 07:57 UTC, Androz2091 commented on structures/Player.js
> +        this.totalgameCount = parseInt($(".info-stats").get(0).children[3].children[0].data.trim().split(" ")[0]);
```suggestion
        this.totalGameCount = parseInt($(".info-stats").get(0).children[3].children[0].data.trim().split(" ")[0]);
```

2020-03-26 14:01 UTC, Hunam6 commented
Fixes made

2020-03-26 14:37 UTC, Hunam6 commented
I'm working on

2020-03-27 07:51 UTC, Androz2091 requested changes
Dernière review normalement, en français parce que c'est plus simple à expliquer. En fait, les getters sont plutôt utilisés pour des propriétés **calculées** en fonction d'autres propriétés __qui sont susceptibles de changer__. Autrement dit, ils simplifient les choses (par exemple pour le `totalGameTime`, il est possible de faire sans et de calculer ça soi-même). La propriété rank, selon moi, serait plus appropriée directement dans le constructor, puisqu'elle n'est pas calculée en fonction d'autres propriétés, et qu'elle ne peut pas changer.

2020-03-27 14:20 UTC, Hunam6 commented
J'ai utilisé le get pour pouvoir bénéficier de la priorité des return.

2020-03-27 15:14 UTC, Androz2091 commented
Il est possible de faire ça dans le constructor, et ce serait beaucoup plus propre : 
```js
const ms = require("human-ms");

module.exports = class SkywarsStats {

    constructor($){
        
        const stats = $(".player-stats-info").get(2);

        this.points = parseInt(stats.children[5].children[3].children[0].data.split(" ").join("")) || 0;
        this.gameCount = parseInt(stats.children[7].children[3].children[0].data.split(" ").join("")) || 0;
        this.top1Count = parseInt(stats.children[9].children[3].children[0].data.split(" ").join("")) || 0;
        this.gameTime = ms(stats.children[11].children[3].children[0].data) || 0;
        this.killCount = parseInt(stats.children[13].children[3].children[0].data.split(" ").join("")) || 0;
        this.deathCount = parseInt(stats.children[15].children[3].children[0].data.split(" ").join("")) || 0;

        this.rank = 0;
        if(!isNaN(parseInt(stats.children[3].children[3].children[0].data))){
            this.rank = parseInt(stats.children[3].children[3].children[0].data);
        } else if(stats.children[3].children[3].children[1]){
            this.rank = parseInt(stats.children[3].children[3].children[1].children[0].data);
        }
    }

    get kd() {
        return (parseFloat(this.killCount/this.deathCount) || 0).toFixed(2);
    }
    
    get wl() {
        return (parseFloat(this.victoryCount / this.defeatCount) || 0).toFixed(2);
    }

    get defeatCount() {
        return parseInt(this.gameCount - this.top1Count) || 0;
    }

};
```

2020-03-28 09:00 UTC, Androz2091 approved these changes
Super PR 😉

2020-03-28 09:01 UTC, merged